-- Treesitter
-- Nvim Treesitter configurations and abstraction layer

return {
    -- Specify repository
    "nvim-treesitter/nvim-treesitter",
    
    -- Build
    build = ":TSUpdate",
    
    -- Lifecycle
    event = { "BufReadPre", "BufNewFile" },

    -- Dependencies
    dependencies = {"windwp/nvim-ts-autotag"},

    -- Configuration
    config = function()
        local treesitter_config = require("nvim-treesitter.configs")
        treesitter_config.setup({

            -- Installed parsers
            ensure_installed = { 
                "c", 
                "lua", 
                "vim", 
                "vimdoc", 
                "query", 
                "elixir", 
                "heex", 
                "javascript", 
                "html",
                "angular",
                "asm",
                "astro",
                "bash",
                "bibtex",
                "bicep",
                "c_sharp",
                "clojure",
                "cmake",
                "comment",
                "cpp",
                "css",
                "csv",
                "cuda",
                "dart",
                "diff",
                "dockerfile",
                "erlang",
                "fortran",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "glsl",
                "go",
                "gomod",
                "gosum",
                "gotmpl",
                "gowork",
                "graphql",
                "groovy",
                "haskell",
                "haskell_persistent",
                "hcl",
                "hlsl",
                "htmldjango",
                "http",
                "ini",
                "java",
                "jq",
                "json",
                "jsdoc",
                "json5",
                "julia",
                "kotlin",
                "latex",
                "llvm",
                "luadoc",
                "make",
                "markdown",
                "markdown_inline",
                "matlab",
                "mermaid",
                "nasm",
                "ocaml",
                "ocaml_interface",
                "ocamllex",
                "odin",
                "pascal",
                "perl",
                "php",
                "php_only",
                "phpdoc",
                "prisma",
                "properties",
                "proto",
                "python",
                "py_manifest",
                "r",
                "regex",
                "ruby",
                "rust",
                "scala",
                "scss",
                "sql",
                "ssh_config",
                "svelte",
                "swift",
                "terraform",
                "textproto",
                "tmux",
                "todotxt",
                "toml",
                "tsx",
                "typescript",
                "vue",
                "wgsl",
                "xml",
                "yaml",
                "zig"
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
            auto_tag = {enable = true},
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<C-space>",
                    node_incremental = "<C-space>",
                    scope_incremental = false,
                    node_decremental = "<bs>",
                },
            },
        })
    end
}
